### ISSUE TITLE
Repo Settings/ GitHub pages Edit button not accessible

### ISSUE THREAD

**Issue by dcossyleon** [dcossyleon/firstclasspackage#2]
Something weird must have happened when I transferred this repo. I'm not unable to edit the link for the page site or access the repo settings. @apreshill 

<img width="1079" alt="Screen Shot 2019-06-17 at 1 03 36 PM" src="https://user-images.githubusercontent.com/29008894/59623203-9312fa00-9101-11e9-9a7d-38c6fb4482c1.png">

**Comment by apreshill** [comment]
check it now, I gave you admin access to the org

**Comment by dcossyleon** [comment]
works now! thanks
